# Generated by Django 3.2.2 on 2021-05-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('cust_name', models.CharField(blank=True, max_length=12, null=True)),
                ('cust_dob', models.DateField(blank=True, null=True)),
                ('cust_street', models.CharField(blank=True, max_length=12, null=True)),
                ('cust_city', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('login_id', models.CharField(max_length=12)),
                ('stu_name', models.CharField(blank=True, max_length=12, null=True)),
                ('stu_level', models.CharField(blank=True, max_length=10, null=True)),
                ('stu_dept', models.CharField(blank=True, max_length=12, null=True)),
                ('stu_mail', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': True,
                'unique_together': {('stu_id', 'login_id')},
            },
        ),
    ]
