# Generated by Django 3.2.2 on 2021-05-26 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210526_1359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usersinfo',
            options={'managed': True},
        ),
    ]
