# Generated by Django 3.2.2 on 2021-05-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210526_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('fac_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('login_id', models.CharField(max_length=12)),
                ('fac_name', models.CharField(blank=True, max_length=12, null=True)),
                ('fac_mail', models.CharField(blank=True, max_length=50, null=True)),
                ('fac_phone_no', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'faculty',
                'managed': True,
                'unique_together': {('fac_id', 'login_id')},
            },
        ),
    ]
