# Generated by Django 3.2.2 on 2021-05-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('login_id', models.CharField(max_length=12)),
                ('admin_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('admin_name', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': True,
                'unique_together': {('admin_id', 'login_id')},
            },
        ),
    ]
